name: Provision Konnect Team resources

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        type: string
        default: 'provision'
      environment:
        description: 'Environment to provision'
        type: string
        default: 'dev'

env:
  KONNECT_RESOURCES_FILE: ${{ github.workspace }}/konnect/resources.yaml
  VAULT_ADDR: ${{ vars.VAULT_ADDR }}
  AWS_ENDPOINT_URL: ${{ vars.AWS_ENDPOINT_URL }}

jobs:
  provision-konnect:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # Required for OIDC token generation
      contents: read    # Required to checkout code

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get secrets from Vault
        uses: hashicorp/vault-action@v3
        id: import-secrets
        with:
          url: https://vault-production-218a.up.railway.app
          method: jwt
          path: github-actions           
          role: flight-operations-gh-repo-role
          exportToken: true  # Key setting!
          secrets: |
            flight-operations-kv/data/system-accounts/sa-flight-operations token | SYSTEM_ACCOUNT_TOKEN ;

      - name: Debug tokens
        run: |
          echo "SYSTEM_ACCOUNT_TOKEN: ${{ steps.import-secrets.outputs.SYSTEM_ACCOUNT_TOKEN }}"
          echo "VAULT_ADDR: ${{ env.VAULT_ADDR }}"
          echo "AWS_ENDPOINT_URL: ${{ vars.AWS_ENDPOINT_URL }}"

      - name: Provision Konnect Resources
        uses: KongHQ-CX/kw-platform-ops/.github/actions/provision-konnect-resources@main
        with:
          action: ${{ inputs.action }}
          config: ${{ env.KONNECT_RESOURCES_FILE }}
          vault_address: ${{ env.VAULT_ADDR }}
          vault_token: ${{ secrets.VAULT_TOKEN }}
          s3_endpoint_url: ${{ vars.AWS_ENDPOINT_URL }}
          s3_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          s3_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          konnect_token: ${{ steps.import-secrets.outputs.SYSTEM_ACCOUNT_TOKEN }}