name: Provision Konnect Team resources

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        type: string
        default: 'provision'
      environment:
        description: 'Environment to provision'
        type: string
        default: 'dev'

env:
  KONNECT_RESOURCES_FILE: ${{ github.workspace }}/konnect/resources.yaml

jobs:
  provision-konnect:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # Required for OIDC token generation
      contents: read    # Required to checkout code

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Method 1: Using HashiCorp's official Vault Action
      - name: Get secrets from Vault
        uses: hashicorp/vault-action@v3
        with:
          url: https://vault-production-218a.up.railway.app
          method: jwt
          path: github-actions                    # The auth path from Terraform
          role: flight-operations-gh-repo-role        # The role name from Terraform
          secrets: |
            flight-operations-kv/data/system-accounts/sa-flight-operations token | SYSTEM_ACCOUNT_TOKEN ;

      # - name: Provision Konnect Resources
      #   uses: ./platform-actions/provision-konnect-resources
      #   with:
      #     action: ${{ inputs.action }}
      #     config: ${{ env.KONNECT_RESOURCES_FILE }}
      #     vault_address: ${{secrets.VAULT_ADDR}} 
      #     vault_token: ${{ secrets.VAULT_TOKEN }}
      #     s3_access_key: ${{ secrets.S3_ACCESS_KEY }}
      #     s3_secret_key: ${{ secrets.S3_SECRET_KEY }}