name: Publish API Configuration to a Control Plane

on:
  workflow_dispatch:
    inputs:
      openapi_spec:
        description: "Path to the OpenAPI Specification file"
        required: true
        type: choice
        default: 'apis/flights/openapi.yaml'
        options:
          - 'apis/routes/openapi.yaml'
          - 'apis/flights/openapi.yaml'
      control_plane_name:
        description: 'Control Plane to deploy kong configuration to'
        required: true
        type: choice
        default: 'flight-operations-dev'
        options:
          - 'flight-operations-dev'
          - 'flight-operations-staging'
          - 'flight-operations-prod'
      api_team_plugins_path:
        description: 'Path to the API team plugins directory'
        required: true
        type: choice
        default: 'apis/flights/plugins'
        options:
          - 'apis/flights/plugins'
          - 'apis/routes/plugins'

jobs:
  publish-api-configuration:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # Required for OIDC token generation
      contents: read    # Required to checkout code

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get secrets from Vault
        uses: hashicorp/vault-action@v3
        id: import-secrets
        with:
          url: ${{ vars.VAULT_ADDR }}
          method: jwt
          path: github-actions           
          role: ${{ vars.KONNECT_TEAM_NAME }}-gh-repo-role
          exportToken: true  # exports the env.VAULT_TOKEN
          secrets: |
            ${{ vars.KONNECT_TEAM_NAME }}-kv/data/system-accounts/sa-${{ vars.KONNECT_TEAM_NAME }} token | SYSTEM_ACCOUNT_TOKEN ;
      
      # - name: Import system account Token from Vault
      #   id: import-token
      #   uses: hashicorp/vault-action@v2
      #   with:
      #     url: ${{ vars.VAULT_ADDR }}
      #     token: ${{ secrets.VAULT_TOKEN }}
      #     secrets: |
      #       ${{ vars.KONNECT_TEAM_NAME }}-kv/data/system-accounts/sa-${{ vars.KONNECT_TEAM_NAME }} token | SYSTEM_ACCOUNT_TOKEN ;


      - name: Publish API Configuration in CP
        uses: KongHQ-CX/kw-platform-ops/.github/actions/publish-api-configuration@main
        with:
          openapi_spec: ${{ inputs.openapi_spec }}
          control_plane_name: ${{ inputs.control_plane_name }}
          system_account_token: ${{ steps.import-token.outputs.SYSTEM_ACCOUNT_TOKEN }}
